---
- name: Create zk data dir
  file: path=/opt/data state=directory
- name: Create zk logs dir
  file: path=/opt/logs/zookeeper state=directory
- name: unarchive gz file
  unarchive: src=zookeeper-3.4.10.tar.gz dest=/opt
- name: cp config sample to zoo.cfg
  copy: src=zoo_sample.cfg dest=/opt/zookeeper-3.4.10/conf/zoo.cfg owner=root group=root
- name: config log path
  lineinfile:
    path: /opt/zookeeper-3.4.10/conf/log4j.properties
    regexp: 'zookeeper.log.dir'
    line: 'zookeeper.log.dir=/opt/logs/zookeeper'
- name: config tracelog path
  lineinfile:
    path: /opt/zookeeper-3.4.10/conf/log4j.properties
    regexp: 'zookeeper.tracelog.dir'
    line: 'zookeeper.tracelog.dir=/opt/logs/zookeeper'
- name: config data path
  lineinfile:
    path: /opt/zookeeper-3.4.10/conf/zoo.cfg
    regexp: 'dataDir=/tmp/zookeeper'
    line: 'dataDir=/opt/data'
- name: Ansible lineinfile mdoule.
  lineinfile:
    path: /opt/data/myid
    with_items: "{{ myid }}"
    state: present
    create: yes
